name:                assetmgr
version:             0.1.0.0
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/whatsupfudd/assetmgr#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  # For dir walk:
  - filepath
  - directory
  - pathwalk
  - unix
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  # For SQL:
  - postgresql-binary
  - hasql
  - hasql-th
  - hasql-pool
  - hasql-transaction
  - profunctors
  # For MD5:
  - pureMD5
  - vector
  # For Cont(T):
  - mtl
  # For Sequunce:
  - containers
  # For S3 storage:
  - minio-hs
  - unliftio
  - conduit
  - http-client
  - primitive
  - memory
  - uuid


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot


ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  assetmgr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assetmgr

tests:
  assetmgr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assetmgr
