resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/44.yaml


# User packages to be built.
packages:
- .

extra-deps:
  - ../../../../Haskell/Minio/minio-hs

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
system-ghc: true
